version: '3.9'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /app/app/manage.py runserver 0.0.0.0:8003
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

